//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: clientmessage.proto
namespace clientmessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgClient")]
  public partial class MsgClient : global::ProtoBuf.IExtensible
  {
    public MsgClient() {}
    
    private uint _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private byte[] _msg = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoginReq")]
  public partial class MsgLoginReq : global::ProtoBuf.IExtensible
  {
    public MsgLoginReq() {}
    
    private byte[] _idkey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"idkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] idkey
    {
      get { return _idkey; }
      set { _idkey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaseCharacter")]
  public partial class BaseCharacter : global::ProtoBuf.IExtensible
  {
    public BaseCharacter() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private uint _money;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private uint _power;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint power
    {
      get { return _power; }
      set { _power = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLoginAck")]
  public partial class MsgLoginAck : global::ProtoBuf.IExtensible
  {
    public MsgLoginAck() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }
    private BaseCharacter _chardata = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chardata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BaseCharacter chardata
    {
      get { return _chardata; }
      set { _chardata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ClientMsgType")]
    public enum ClientMsgType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_LoginReq", Value=1)]
      Msg_LoginReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_LoginAck", Value=2)]
      Msg_LoginAck = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_CreateCharReq", Value=3)]
      Msg_CreateCharReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_CreateCharAck", Value=4)]
      Msg_CreateCharAck = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_Offline", Value=5)]
      Msg_Offline = 5
    }
  
}